/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.UsuarioDAO;
import Model.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author zpeed
 */
public class TelaCadastroUsuario extends javax.swing.JFrame {

  /**
   * Creates new form TelaCadastroUsuario
   */
  public TelaCadastroUsuario () {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    nomeTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    btnCadastrar = new javax.swing.JButton();
    btnVoltar = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    senhaPF = new javax.swing.JPasswordField();
    confirmaSenhaPF = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    nomeTextField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nomeTextFieldActionPerformed(evt);
      }
    });

    jLabel1.setText("Nome");

    jLabel3.setText("Senha");

    btnCadastrar.setText("Cadastrar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    btnVoltar.setText("Voltar");

    jLabel4.setText("Confirmar senha");

    senhaPF.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        senhaPFActionPerformed(evt);
      }
    });

    confirmaSenhaPF.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirmaSenhaPFActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(16, 16, 16)
            .addComponent(btnVoltar))
          .addGroup(layout.createSequentialGroup()
            .addGap(89, 89, 89)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel3)
              .addComponent(jLabel1)
              .addComponent(nomeTextField)
              .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
              .addComponent(jLabel4)
              .addComponent(senhaPF)
              .addComponent(confirmaSenhaPF))))
        .addContainerGap(108, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(14, 14, 14)
        .addComponent(btnVoltar)
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(senhaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(4, 4, 4)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(confirmaSenhaPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnCadastrar)
        .addContainerGap(62, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_nomeTextFieldActionPerformed

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    // TODO add your handling code here:
    String nome = nomeTextField.getText();
    String senha = new String (senhaPF.getPassword()) ;
    String confirmaSenha = new String (confirmaSenhaPF.getPassword());
    
    System.out.println(senha);
    System.out.println(confirmaSenha);
    
    if (!confirmaSenha.equals(senha)) {
      JOptionPane.showMessageDialog(null, "Senhas devem ser iguais!");
    }
    
    try {
      Usuario usuario = new Usuario(nome, senha);
      UsuarioDAO usuarioDAO = new UsuarioDAO();
      
      usuarioDAO.cadastrar(usuario);
      
      JOptionPane.showMessageDialog(null, "Cadastro realizado! Faça login.");
 
      TelaLogin login = new TelaLogin();
      login.setVisible(true);
      this.dispose();
      
    } catch (Exception e) {
      JOptionPane.showMessageDialog(null, "Erro ao cadastrar");
    }
  }//GEN-LAST:event_btnCadastrarActionPerformed

  private void senhaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaPFActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_senhaPFActionPerformed

  private void confirmaSenhaPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaSenhaPFActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_confirmaSenhaPFActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main (String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaCadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run () {
        new TelaCadastroUsuario().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JButton btnVoltar;
  private javax.swing.JPasswordField confirmaSenhaPF;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField nomeTextField;
  private javax.swing.JPasswordField senhaPF;
  // End of variables declaration//GEN-END:variables
}
